### ISSUE TITLE
0.3.0 TODO list

### ISSUE THREAD

**Issue by yangrc1234** [yangrc1234/UE4-Details-Workspace#1]
- [x] Improve UI, drag important functions out of config area.  
- [x] Support multiple DetailsWorksapce window instances.  
    * It's supported by default, just add more buttons to open different instances.  
- [x] Redirect UE4 "TransformCommon" category to "Transform" when displaying categories, for less confusion.
- [x] Add search box in layout selection menu. 
- [x] Update welcome window content.  
- [x] Update README and its images.  
- [x] Test before release.
